version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: aphromas_db
    environment:
      MYSQL_ROOT_PASSWORD: Root@password123
      MYSQL_DATABASE: aphromasdiamondv1
    ports:
      - '3306:3306'
    volumes:
      - db_vol:/var/lib/mysql
    restart: always
    networks:
      - aphromas_net

  backend:
    container_name: aphromas_api
    image: phanlong166/aphromas-be:latest
    build:
      context: ./AphromasDiamondV1BE
      dockerfile: Dockerfile
    env_file:
      - ./.env.be
    ports:
      - '3000:3000'
    restart: always
    networks:
      - aphromas_net

  frontend:
    container_name: aphromas_fe
    image: phanlong166/aphromas-fe:latest
    build: 
      context: ./AphromasDiamond_FE
      dockerfile: Dockerfile
    env_file:
      - ./.env.fe
    ports:
      - 5173:80
    restart: always
    networks:
      - aphromas_net

networks:
  aphromas_net:
    driver: bridge

volumes:
  db_vol: 
