version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: aphromasdiamondv1
      MYSQL_PASSWORD: 123456
    ports:
      - '3306:3306'
    restart: always
    networks:
      - aphromas_net

  backend:
    container_name: aphromas_api
    image: phanlong166/aphromas-be:latest
    build:
      context: ./AphromasDiamondV1BE
      dockerfile: Dockerfile
    env_file:
      - ./.env.be
    ports:
      - '3000:3000'
    restart: always
    networks:
      - aphromas_net

  frontend:
    container_name: aphromas_fe
    image: phanlong166/aphromas-fe:latest
    build: 
      context: ./AphromasDiamond_FE
      dockerfile: Dockerfile
    env_file:
      - ./.env.fe
    ports:
      - 8080:80
    restart: always
    networks:
      - aphromas_net

networks:
  aphromas_net:
    driver: bridge

